paste command should return just the hashes of removed
The paste command should just return the hashes of the removed files rather than full details. This was causing an error when dragging a file between folders and the file wouldn’t be removed from the interface. The error was:

    Error: Syntax error, unrecognized expression: #[object ]